// react-spa-pb/src/components/Category.tsx
import { ExpandedCategory, useDataQuery } from "@/hooks/useDataQuery";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";
import { Input } from "./ui/input";
import { Button, buttonVariants } from "./ui/button";
import { GripVertical, Plus, X } from "lucide-react";
import { CategoryItem } from "./CategoryItem";
import { RecordModel } from "pocketbase";
import { Checkbox } from "./ui/checkbox";
import {
  SortableContext,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { cn } from "@/lib/utils";
import { CSS } from "@dnd-kit/utilities";

interface Props {
  list: RecordModel;
  category: ExpandedCategory;
}

const schema = z.object({
  name: z.string(),
});

export const Category: React.FC<Props> = (props) => {
  const { category, list } = props;
  const {
    updateCategory,
    deleteCategory,
    packCategoryItems,
    createCategoryItem,
  } = useDataQuery();

  const methods = useForm({
    resolver: zodResolver(schema),
    values: category,
  });

  const { handleSubmit, control } = methods;

  const saveCategory = (data: ExpandedCategory) => {
    updateCategory.mutate({ id: category.id, data });
  };

  const { attributes, listeners, setNodeRef, transform, transition } =
    useSortable({ id: category.id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  const categoryPacked =
    category.items.length > 0 && category.items.every((i) => i.packed);

  return (
    <article ref={setNodeRef} {...attributes}>
      <div
        className="border-b-2 p-1 grid gap-1 items-center text-sm font-semibold group"
        style={{
          ...style,
          gridTemplateColumns: `${list.show_packed ? "auto" : ""} 1fr ${
            list.show_weights ? "6rem" : ""
          } 4rem auto auto`,
        }}
      >
        {list.show_packed && (
          <Checkbox
            checked={categoryPacked}
            onCheckedChange={(checked) =>
              packCategoryItems.mutate({ category, packed: Boolean(checked) })
            }
          />
        )}
        <form
          onBlur={handleSubmit(saveCategory)}
          onSubmit={handleSubmit(saveCategory)}
          className="flex-1"
        >
          <Controller
            control={control}
            name="name"
            render={({ field }) => (
              <Input
                {...field}
                placeholder="Category Name"
                className="font-semibold text-primary border-none shadow-none text-base"
              />
            )}
          />
          <input type="hidden" />
        </form>
        {list.show_weights && <div className="text-foreground/70">Weight</div>}
        <div className="text-foreground/70">Qty</div>
        <Button
          size="icon"
          variant="ghost"
          className="w-6 text-destructive hover:text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
          onClick={() => deleteCategory.mutate(category.id)}
        >
          <X className="h-4 w-4" />
        </Button>
        <div
          className={cn(
            buttonVariants({ variant: "ghost", size: "icon" }),
            "hover:text-foreground text-muted-foreground w-6"
          )}
          {...listeners}
        >
          <GripVertical className="h-4 w-4" />
        </div>
      </div>
      <SortableContext
        items={category.items}
        strategy={verticalListSortingStrategy}
      >
        {category.items.map((item) => (
          <CategoryItem key={item.id} list={list} item={item} />
        ))}
      </SortableContext>
      <div className="mt-2">
        <Button
          variant="linkMuted"
          size="sm"
          onClick={() => createCategoryItem.mutate(category.id)}
        >
          <Plus className="h-4 w-4 mr-2" />
          Add Item
        </Button>
      </div>
    </article>
  );
};

// client/src/components/list/Category.svelte
<script lang="ts">
	import {
		useDeleteCategory,
		useToggleCategoryPacked,
		useUpdateCategory
	} from '@/hooks/useCategory';
	import { Checkbox } from '@/components/ui/checkbox';
	import { Button } from '@/components/ui/button';
	import { Plus } from 'lucide-svelte';
	import type { ExpandedCategory, ExpandedCategoryItem, ListWithCategories } from '@/hooks/useList';
	import CategoryItem from './CategoryItem.svelte';
	import {
		createCategoryTemplateCols,
		createTempCategoryItem,
		formatWeight,
		getCategoryWeight,
		isCategoryFullyPacked,
		transformDraggedElement
	} from '@/lib/helpers';
	import { useCreateCategoryItem, useUpdateCategoryItemsOrder } from '@/hooks/useCategoryItem';
	import {
		SHADOW_ITEM_MARKER_PROPERTY_NAME,
		SHADOW_PLACEHOLDER_ITEM_ID,
		dndzone
	} from 'svelte-dnd-action';
	import { Input } from '@/components/ui/input';
	import DeleteButton from '@/components/base/DeleteButton.svelte';
	import { CATEGORY_NAME_CLASS, DRAGGABLE_CLASS, flipDurationMs } from '@/lib/constants';
	import DragHandle from '@/components/base/DragHandle.svelte';
	import DragGhost from '@/components/base/DragGhost.svelte';
	import { isForeignItem } from '@/lib/store';
	import type { ItemsResponse } from '@/lib/types';

	export let category: ExpandedCategory;
	export let list: ListWithCategories;

	type CategorItemWithShadowItem = ExpandedCategoryItem & {
		[SHADOW_ITEM_MARKER_PROPERTY_NAME]?: string;
	};

	$: categoryItems = (category.items ?? []) as CategorItemWithShadowItem[];

	$: updateCategory = useUpdateCategory();
	$: deleteCategory = useDeleteCategory();
	$: toggleCategoryPacked = useToggleCategoryPacked();
	$: createCategoryItem = useCreateCategoryItem();
	$: updateCategoryItemsOrder = useUpdateCategoryItemsOrder();

	$: saveCategory = () => $updateCategory.mutate({ id: category.id, category });

	const handleConsider = async (ev: CustomEvent<DndEvent<ExpandedCategoryItem>>) => {
		if ($isForeignItem) {
			categoryItems = ev.detail.items.map((item) =>
				item.id === SHADOW_PLACEHOLDER_ITEM_ID
					? {
							...item,
							...createTempCategoryItem(item as unknown as ItemsResponse)
						}
					: item
			);
			return;
		}
		categoryItems = ev.detail.items;
	};

	const handleFinalize = async (ev: CustomEvent<DndEvent<ExpandedCategoryItem>>) => {
		const { id } = ev.detail.info;

		if ($isForeignItem) {
			const insertionIndex = categoryItems.findIndex(
				(item) => item.id === SHADOW_PLACEHOLDER_ITEM_ID
			);
			$createCategoryItem.mutate({
				category,
				listId: list.id,
				itemId: id,
				insertionIndex
			});
			return;
		}

		categoryItems = ev.detail.items;
		const ids = ev.detail.items.map((item) => item.id);
		$updateCategoryItemsOrder.mutate({
			categoryItemIds: ids,
			categoryId: category.id
		});
	};
</script>

<article class={DRAGGABLE_CLASS} id={category.id}>
	<header
		class="grid items-center gap-2 border-b-2 px-2 py-1 text-sm font-semibold"
		style="grid-template-columns: {createCategoryTemplateCols({
			list,
			type: 'header'
		})}"
	>
		{#if list.show_packed}
			<Checkbox
				checked={isCategoryFullyPacked(category)}
				onCheckedChange={() => $toggleCategoryPacked.mutate(category)}
			/>
		{/if}
		<form on:submit|preventDefault={saveCategory} class="flex-1">
			<Input
				bind:value={category.name}
				on:blur={saveCategory}
				placeholder="Category Name"
				class="{CATEGORY_NAME_CLASS} text-primary h-auto w-full border-none bg-inherit py-0.5 text-base font-semibold shadow-none placeholder:italic"
			/>
			<input type="hidden" />
		</form>
		{#if list.show_weights}
			<div class="text-foreground/70 text-center">Weight</div>
		{/if}

		<div class="text-foreground/70 text-center">Qty</div>
		<DeleteButton handleDelete={() => $deleteCategory.mutate(category)} />
		<DragHandle />
	</header>
	<div
		class="min-h-[0.5rem] rounded"
		use:dndzone={{
			items: categoryItems,
			type: 'items',
			dropTargetStyle: {},
			dragDisabled: categoryItems.length === 0,
			flipDurationMs,
			transformDraggedElement
		}}
		on:consider={handleConsider}
		on:finalize={handleFinalize}
	>
		{#each categoryItems as categoryItem (categoryItem.id)}
			<div class="relative">
				<CategoryItem {list} {categoryItem} />
				{#if categoryItem[SHADOW_ITEM_MARKER_PROPERTY_NAME]}
					<DragGhost />
				{/if}
			</div>
		{/each}
		{#if categoryItems.length === 0}
			<p
				class="text-muted-foreground flex w-full items-center justify-center border-b p-4 text-xs"
				draggable="false"
			>
				No items
			</p>
		{/if}
	</div>
	<footer
		class="grid items-center gap-2 border-t px-2 text-sm"
		style="grid-template-columns: {createCategoryTemplateCols({
			list,
			type: 'footer'
		})};"
	>
		<Button
			size="sm"
			class="w-min"
			variant="linkMuted"
			on:click={() => $createCategoryItem.mutate({ category, listId: list.id })}
			disabled={$createCategoryItem.isPending}
		>
			<Plus class="mr-2 h-4 w-4" />
			Add Item
		</Button>
		{#if list.show_weights}
			<div class="flex gap-2 justify-self-end pr-6 font-semibold">
				<p>
					{formatWeight(getCategoryWeight(category, list.weight_unit))}
				</p>
				<p>{list.weight_unit}</p>
			</div>
		{/if}
		<div class="pr-5 text-right font-semibold">
			{category.items.reduce((acc, val) => acc + val.quantity, 0)}
		</div>
	</footer>
</article>
