// client-react/src/components/list-settings.tsx
import React from "react";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import { Settings } from "lucide-react";
import { Button } from "./ui/button";
import {
  Collections,
  ListsResponse,
  ListsWeightUnitOptions,
} from "@/lib/types";
import { useMutation } from "react-query";
import { updateList } from "@/api/list";
import { queryClient } from "@/lib/query";

interface Props {
  list: ListsResponse;
}

const ListSettings: React.FC<Props> = (props) => {
  const { list } = props;

  const updateMutation = useMutation({
    mutationFn: (data: Partial<ListsResponse>) =>
      updateList({ id: list.id, list: data }),
    onSuccess: () => {
      queryClient.invalidateQueries([Collections.Lists, list.id]);
    },
  });

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost">
          <Settings className="mr-2 h-4 w-4" />
          Settings
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-52">
        <DropdownMenuLabel>List Settings</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuSub>
          <DropdownMenuSubTrigger>Default unit of mass</DropdownMenuSubTrigger>
          <DropdownMenuSubContent>
            <DropdownMenuRadioGroup
              value={list.weight_unit}
              onValueChange={(value) =>
                updateMutation.mutate({
                  weight_unit: value as ListsWeightUnitOptions,
                })
              }
            >
              {Object.values(ListsWeightUnitOptions).map((massUnit) => (
                <DropdownMenuRadioItem value={massUnit}>
                  {massUnit}
                </DropdownMenuRadioItem>
              ))}
            </DropdownMenuRadioGroup>
          </DropdownMenuSubContent>
        </DropdownMenuSub>
        <DropdownMenuSeparator />
        <DropdownMenuCheckboxItem
          checked={list.show_packed}
          onCheckedChange={(checked) =>
            updateMutation.mutate({
              show_packed: checked,
            })
          }
        >
          Show Packed
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          checked={list.show_images}
          onCheckedChange={(checked) =>
            updateMutation.mutate({
              show_images: checked,
            })
          }
        >
          Show Images
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          checked={list.show_weights}
          onCheckedChange={(checked) =>
            updateMutation.mutate({
              show_weights: checked,
            })
          }
        >
          Show Weight
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          disabled
          checked={list.show_prices}
          onCheckedChange={(checked) =>
            updateMutation.mutate({
              show_prices: checked,
            })
          }
        >
          Show Prices
        </DropdownMenuCheckboxItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ListSettings;

// client/src/components/list/ListSettings.svelte
<script lang="ts">
	import { Settings } from 'lucide-svelte';
	import { Button } from '@/components/ui/button';
	import {
		DropdownMenu,
		DropdownMenuCheckboxItem,
		DropdownMenuContent,
		DropdownMenuLabel,
		DropdownMenuRadioGroup,
		DropdownMenuRadioItem,
		DropdownMenuSeparator,
		DropdownMenuSub,
		DropdownMenuSubContent,
		DropdownMenuSubTrigger,
		DropdownMenuTrigger
	} from '@/components/ui/dropdown-menu';
	import { useUpdateList, type ListWithCategories } from '@/hooks/useList';
	import { ItemsWeightUnitOptions } from '@/lib/types';

	let bookmarks = false;
	let fullUrls = true;

	const profileRadioValue = 'benoit';

	export let list: ListWithCategories;

	$: updateList = useUpdateList();
	$: saveList = () => $updateList.mutate({ id: list.id, list });
</script>

<DropdownMenu>
	<DropdownMenuTrigger asChild let:builder>
		<Button builders={[builder]} size="icon" variant="ghost">
			<Settings class="h-4 w-4" />
		</Button>
	</DropdownMenuTrigger>
	<DropdownMenuContent class="w-52">
		<DropdownMenuLabel>List Settings</DropdownMenuLabel>
		<DropdownMenuSeparator />
		<DropdownMenuSub>
			<DropdownMenuSubTrigger>Default unit of mass</DropdownMenuSubTrigger>
			<DropdownMenuSubContent>
				<DropdownMenuRadioGroup bind:value={list.weight_unit} onValueChange={saveList}>
					{#each Object.values(ItemsWeightUnitOptions) as massUnit}
						<DropdownMenuRadioItem value={massUnit}>
							{massUnit}
						</DropdownMenuRadioItem>
					{/each}
				</DropdownMenuRadioGroup>
			</DropdownMenuSubContent>
		</DropdownMenuSub>
		<DropdownMenuSeparator />
		<DropdownMenuCheckboxItem bind:checked={list.show_packed} onCheckedChange={saveList}>
			Show Packed
		</DropdownMenuCheckboxItem>
		<DropdownMenuCheckboxItem bind:checked={list.show_images} onCheckedChange={saveList}>
			Show Images
		</DropdownMenuCheckboxItem>
		<DropdownMenuCheckboxItem bind:checked={list.show_weights} onCheckedChange={saveList}>
			Show Weight
		</DropdownMenuCheckboxItem>
		<DropdownMenuCheckboxItem bind:checked={list.show_prices} onCheckedChange={saveList}>
			Show Prices
		</DropdownMenuCheckboxItem>
	</DropdownMenuContent>
</DropdownMenu>
