// client/src/components/PackingLists.svelte
<script lang="ts">
	import { Loader2, Plus } from 'lucide-svelte';
	import { Button } from '@/components/ui/button';

	import { useCreateList, useLists, useUpdateListsOrder } from '@/hooks/useList';
	import { SHADOW_ITEM_MARKER_PROPERTY_NAME, dndzone } from 'svelte-dnd-action';
	import { Collections, type ListsResponse } from '@/lib/types';
	import { flip } from 'svelte/animate';
	import { flipDurationMs } from '@/lib/constants';
	import ListListItem from './PackingList.svelte';
	import DragGhost from '@/components/base/DragGhost.svelte';
	import { transformDraggedElement } from '@/lib/helpers';
	import { createQuery } from '@tanstack/svelte-query';
	import { getLists } from '@/api/list';
	import IconTitleSubtitle from './base/IconTitleSubtitle.svelte';
	import Loader from './base/Loader.svelte';

	type ListWithShadowItem = ListsResponse & {
		[SHADOW_ITEM_MARKER_PROPERTY_NAME]?: string;
	};

	$: listsQuery = createQuery({
		queryFn: getLists,
		queryKey: [Collections.Lists]
	});
	$: createList = useCreateList();

	$: listData = ($listsQuery.data ?? []) as ListWithShadowItem[];

	$: updateListOrder = useUpdateListsOrder();
	const handleConsider = (ev: CustomEvent<DndEvent<ListsResponse>>) => {
		listData = ev.detail.items;
	};

	const handleFinalize = (ev: CustomEvent<DndEvent<ListsResponse>>) => {
		listData = ev.detail.items;
		const ids = ev.detail.items.map((item) => item.id);
		$updateListOrder.mutate({ listIds: ids });
	};
</script>

<section class="flex h-full max-h-[40vh] flex-1 flex-col gap-2 p-4">
	<div class="flex items-center justify-between">
		<h2 class="text-sm font-medium">Lists</h2>
		<Button size="sm" variant="linkMuted" on:click={() => $createList.mutate()}>
			<Plus class="mr-2 w-4" /> New List
		</Button>
	</div>
	<div
		use:dndzone={{
			items: listData,
			type: 'lists',
			flipDurationMs,
			dropTargetStyle: {},
			dropTargetClasses: ['border-primary'],
			transformDraggedElement
		}}
		on:consider={handleConsider}
		on:finalize={handleFinalize}
		class="bg-card h-full overflow-y-auto rounded-md border py-2 transition-colors"
	>
		{#if $listsQuery.isSuccess}
			{#each listData as list (list.id)}
				<div animate:flip={{ duration: flipDurationMs }} class="relative">
					<ListListItem {list} />
					{#if list[SHADOW_ITEM_MARKER_PROPERTY_NAME]}
						<DragGhost fullWidth />
					{/if}
				</div>
			{/each}
			{#if listData.length === 0}
				<p class="text-muted-foreground flex h-full items-center justify-center p-6 text-sm">
					No lists
				</p>
			{/if}
		{/if}

		{#if $listsQuery.isLoading}
			<Loader />
		{/if}
	</div>
</section>

// astro/src/components/packing-lists.tsx
import { createList, getLists, updateListsOrder } from "@/actions/list";
import { queryClient } from "@/lib/query";
import { Collections, type ListsResponse } from "@/lib/types";
import { Plus } from "lucide-react";
import React from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Button } from "./ui/button";
import { Card } from "./ui/card";
import PackingList from "./packing-list";
import Loader from "./base/loader";
import Error from "./base/error";

import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
  DragOverlay,
  type DragStartEvent,
} from "@dnd-kit/core";
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { cn, getPaths } from "@/lib/utils";
import Placeholder from "./base/placeholder";

export default function PackingLists(): ReturnType<React.FC> {
  const navigate = useNavigate();

  const [activeList, setActiveList] = React.useState<ListsResponse | null>(
    null
  );

  const listsQuery = useQuery<ListsResponse[], Error>({
    queryKey: [Collections.Lists],
    queryFn: getLists,
  });

  const newListMutation = useMutation({
    mutationFn: createList,
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: [Collections.Lists] });
      navigate(getPaths.list(data.id));
    },
  });

  const reorderListsMutation = useMutation({
    mutationFn: (lists: ListsResponse[]) =>
      updateListsOrder(lists.map((i) => i.id)),
    onMutate: async (newLists) => {
      await queryClient.cancelQueries({ queryKey: [Collections.Lists] });
      const previousLists = queryClient.getQueryData([Collections.Lists]);
      queryClient.setQueryData([Collections.Lists], newLists);
      return { previousLists };
    },
    onError: (_, __, context) => {
      if (context?.previousLists)
        queryClient.setQueryData([Collections.Lists], context.previousLists);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [Collections.Lists] });
    },
  });

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  function handleDragStart(event: DragStartEvent) {
    if (!listsQuery.isSuccess) return;
    const active = listsQuery.data.find((i) => i.id === event.active.id);
    if (active) setActiveList(active);
  }

  function handleDragEnd(event: DragEndEvent) {
    const { active, over } = event;
    setActiveList(null);
    if (active.id === over?.id || !listsQuery.isSuccess) return;

    const oldIndex = listsQuery.data.findIndex((i) => i.id === active.id);
    const newIndex = listsQuery.data.findIndex((i) => i.id === over?.id);

    const newData = arrayMove(listsQuery.data, oldIndex, newIndex);
    reorderListsMutation.mutate(newData);
  }

  return (
    <div className="flex flex-col h-full gap-2 p-4">
      <header className="flex items-center justify-between">
        <span className="font-semibold text-sm">Lists</span>
        <Button
          size="sm"
          variant="linkMuted"
          onClick={() => newListMutation.mutate()}
        >
          <Plus size="1rem" className="mr-2" />
          Add List
        </Button>
      </header>
      <Card
        className={cn(
          "py-2 h-full overflow-y-auto overflow-x-hidden transition-colors",
          activeList && "border-primary"
        )}
      >
        {listsQuery.isLoading && <Loader />}
        {listsQuery.isError && <Error error={listsQuery.error} />}
        {listsQuery.isSuccess && (
          <DndContext
            sensors={sensors}
            collisionDetection={closestCenter}
            onDragEnd={handleDragEnd}
            onDragStart={handleDragStart}
          >
            <SortableContext
              id="packing-lists"
              items={listsQuery.data}
              strategy={verticalListSortingStrategy}
            >
              {listsQuery.data?.map((list) => (
                <PackingList key={list.id} list={list} />
              ))}
            </SortableContext>
            <DragOverlay dropAnimation={null}>
              {activeList && <PackingList list={activeList} isOverlay />}
            </DragOverlay>
          </DndContext>
        )}
        {listsQuery.isSuccess && listsQuery.data.length === 0 && (
          <Placeholder message="No lists yet" />
        )}
      </Card>
    </div>
  );
}
