// svelte-spa-pb/src/components/Category.svelte
<script lang="ts">
  import { useDeleteCategory, useUpdateCategory } from "@/hooks/useCategory";
  import { useQueryClient } from "@tanstack/svelte-query";
  import type { RecordModel } from "pocketbase";
  import { Checkbox } from "./ui/checkbox";
  import { Button } from "./ui/button";
  import { Input } from "./ui/input";
  import { GripVertical, Plus, X } from "lucide-svelte";
  import type { ExpandedCategory } from "@/hooks/useList";
  import CategoryItem from "./CategoryItem.svelte";

  export let category: ExpandedCategory;
  export let list: RecordModel;

  const queryClient = useQueryClient();
  const updateCategory = useUpdateCategory(queryClient);
  const deleteCategory = useDeleteCategory(queryClient);

  $: saveCategory = () => $updateCategory.mutate(category);
</script>

<article>
  <div
    class="border-b-2 p-1 flex gap-1 items-center text-sm font-semibold group"
  >
    <!-- {#if list.show_packed}
      <Checkbox
        bind:checked={categoryPacked}
        onCheckedChange={(checked) =>
          packCategoryItems.mutate({ category, packed: Boolean(checked) })}
      />
    {/if} -->
    <form on:submit|preventDefault={saveCategory} class="flex-1">
      <Input
        bind:value={category.name}
        on:blur={saveCategory}
        placeholder="Category Name"
        class="font-semibold text-primary border-none shadow-none text-base"
      />
      <input type="hidden" />
    </form>
    {#if list.show_weights}
      <div class="text-foreground/70">Weight</div>
    {/if}

    <div class="text-foreground/70">Qty</div>
    <Button
      size="icon"
      variant="ghost"
      class="w-6 text-destructive hover:text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
      on:click={() => $deleteCategory.mutate(category)}
    >
      <X class="h-4 w-4" />
    </Button>
    <div>
      <GripVertical class="h-4 w-4" />
    </div>
  </div>
  {#each category.items as categoryItem}
    <CategoryItem {list} {categoryItem} />
  {/each}

  <div class="mt-2">
    <Button variant="linkMuted" size="sm">
      <!-- on:click={() => createCategoryItem.mutate(category.id)}
      disabled={createCategoryItem.isPending} -->
      <Plus class="h-4 w-4 mr-2" />
      Add Item
    </Button>
  </div>
</article>

// react-spa-pb/src/components/Category.tsx
import { ExpandedCategory, useDataQuery } from "@/hooks/useDataQuery";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";
import { Input } from "./ui/input";
import { Button, buttonVariants } from "./ui/button";
import { GripVertical, Plus, X } from "lucide-react";
import { CategoryItem } from "./CategoryItem";
import { RecordModel } from "pocketbase";
import { Checkbox } from "./ui/checkbox";
import {
  SortableContext,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { cn } from "@/lib/utils";
import { CSS } from "@dnd-kit/utilities";

interface Props {
  list: RecordModel;
  category: ExpandedCategory;
}

const schema = z.object({
  name: z.string(),
});

export const Category: React.FC<Props> = (props) => {
  const { category, list } = props;
  const {
    updateCategory,
    deleteCategory,
    packCategoryItems,
    createCategoryItem,
  } = useDataQuery();

  const methods = useForm({
    resolver: zodResolver(schema),
    values: category,
  });

  const { handleSubmit, control } = methods;

  const saveCategory = (data: ExpandedCategory) => {
    updateCategory.mutate({ id: category.id, data });
  };

  const { attributes, listeners, setNodeRef, transform, transition } =
    useSortable({ id: category.id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  const categoryPacked =
    category.items.length > 0 && category.items.every((i) => i.packed);

  return (
    <article ref={setNodeRef} {...attributes}>
      <div
        className="border-b-2 p-1 grid gap-1 items-center text-sm font-semibold group"
        style={{
          ...style,
          gridTemplateColumns: `${list.show_packed ? "auto" : ""} 1fr ${
            list.show_weights ? "6rem" : ""
          } 4rem auto auto`,
        }}
      >
        {list.show_packed && (
          <Checkbox
            checked={categoryPacked}
            onCheckedChange={(checked) =>
              packCategoryItems.mutate({ category, packed: Boolean(checked) })
            }
          />
        )}
        <form
          onBlur={handleSubmit(saveCategory)}
          onSubmit={handleSubmit(saveCategory)}
          className="flex-1"
        >
          <Controller
            control={control}
            name="name"
            render={({ field }) => (
              <Input
                {...field}
                placeholder="Category Name"
                className="font-semibold text-primary border-none shadow-none text-base"
              />
            )}
          />
          <input type="hidden" />
        </form>
        {list.show_weights && <div className="text-foreground/70">Weight</div>}
        <div className="text-foreground/70">Qty</div>
        <Button
          size="icon"
          variant="ghost"
          className="w-6 text-destructive hover:text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
          onClick={() => deleteCategory.mutate(category.id)}
        >
          <X className="h-4 w-4" />
        </Button>
        <div
          className={cn(
            buttonVariants({ variant: "ghost", size: "icon" }),
            "hover:text-foreground text-muted-foreground w-6"
          )}
          {...listeners}
        >
          <GripVertical className="h-4 w-4" />
        </div>
      </div>
      <SortableContext
        items={category.items}
        strategy={verticalListSortingStrategy}
      >
        {category.items.map((item) => (
          <CategoryItem key={item.id} list={list} item={item} />
        ))}
      </SortableContext>
      <div className="mt-2">
        <Button
          variant="linkMuted"
          size="sm"
          onClick={() => createCategoryItem.mutate(category.id)}
        >
          <Plus className="h-4 w-4 mr-2" />
          Add Item
        </Button>
      </div>
    </article>
  );
};
