// client/src/components/Category.svelte
<script lang="ts">
  import {
    useDeleteCategory,
    useToggleCategoryPacked,
    useUpdateCategory,
  } from "@/hooks/useCategory";
  import { useQueryClient } from "@tanstack/svelte-query";
  import type { RecordModel } from "pocketbase";
  import { Checkbox } from "./ui/checkbox";
  import { Button } from "./ui/button";
  import { Input } from "./ui/input";
  import { GripVertical, Plus, X } from "lucide-svelte";
  import type { ExpandedCategory } from "@/hooks/useList";
  import CategoryItem from "./CategoryItem.svelte";
  import { isCategoryFullyPacked } from "@/lib/helpers";
  import { useCreateCategoryItem } from "@/hooks/useCategoryItem";

  export let category: ExpandedCategory;
  export let list: RecordModel;

  const queryClient = useQueryClient();

  $: updateCategory = useUpdateCategory(queryClient);
  $: deleteCategory = useDeleteCategory(queryClient);
  $: toggleCategoryPacked = useToggleCategoryPacked(queryClient);
  $: createCategoryItem = useCreateCategoryItem(queryClient);

  $: saveCategory = () => $updateCategory.mutate(category);
</script>

<article>
  <div
    class="border-b-2 p-1 grid gap-1 items-center text-sm font-semibold"
    style="grid-template-columns: {list.show_packed
      ? 'auto'
      : ''} 1fr {list.show_weights ? '6rem' : ''} 4rem auto auto;"
  >
    {#if list.show_packed}
      <Checkbox
        checked={isCategoryFullyPacked(category)}
        onCheckedChange={() => $toggleCategoryPacked.mutate(category)}
      />
    {/if}
    <form on:submit|preventDefault={saveCategory} class="flex-1">
      <Input
        bind:value={category.name}
        on:blur={saveCategory}
        placeholder="Category Name"
        class="font-semibold text-primary border-none shadow-none text-base"
      />
      <input type="hidden" />
    </form>
    {#if list.show_weights}
      <div class="text-foreground/70">Weight</div>
    {/if}

    <div class="text-foreground/70">Qty</div>
    <Button
      size="icon"
      variant="ghost"
      class="w-6 h-6 rounded-full"
      on:click={() => $deleteCategory.mutate(category)}
    >
      <X class="h-4 w-4" />
    </Button>
    <div>
      <GripVertical class="h-4 w-4 text-muted-foreground" />
    </div>
  </div>
  {#each category.items as categoryItem}
    <CategoryItem {list} {categoryItem} />
  {/each}

  <div class="mt-2">
    <Button
      variant="linkMuted"
      size="sm"
      on:click={() => $createCategoryItem.mutate(category)}
      disabled={$createCategoryItem.isPending}
    >
      <Plus class="h-4 w-4 mr-2" />
      Add Item
    </Button>
  </div>
</article>

// react-spa-pb/src/components/Category.tsx
import { ExpandedCategory, useDataQuery } from "@/hooks/useDataQuery";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";
import { Input } from "./ui/input";
import { Button } from "./ui/button";
import { Delete, Plus } from "lucide-react";
import { CategoryItem } from "./CategoryItem";
import { RecordModel } from "pocketbase";
import { Checkbox } from "./ui/checkbox";

interface Props {
  list: RecordModel;
  category: ExpandedCategory;
}

const schema = z.object({
  name: z.string(),
});

export const Category: React.FC<Props> = (props) => {
  const { category, list } = props;
  const { updateCategory, deleteCategory, packCategoryItems } = useDataQuery();

  const methods = useForm({
    resolver: zodResolver(schema),
    values: category,
  });

  const { handleSubmit, control } = methods;

  const saveCategory = (data: ExpandedCategory) => {
    updateCategory.mutate({ id: category.id, data });
  };

  const categoryPacked =
    category.items.length > 0 && category.items.every((i) => i.packed);

  return (
    <article>
      <div
        className="border-b-2 p-1 grid gap-2 items-center group text-sm font-semibold"
        style={{
          gridTemplateColumns: `${
            list.show_packed ? "auto" : ""
          } 1fr 6rem 4rem auto`,
        }}
      >
        <Checkbox
          checked={categoryPacked}
          onCheckedChange={(checked) =>
            packCategoryItems.mutate({ category, packed: Boolean(checked) })
          }
        />
        <form
          onBlur={handleSubmit(saveCategory)}
          onSubmit={handleSubmit(saveCategory)}
          className="flex-1"
        >
          <Controller
            control={control}
            name="name"
            render={({ field }) => (
              <Input
                {...field}
                placeholder="Category Name"
                className="font-semibold text-accent-foreground border-none shadow-none text-base"
              />
            )}
          />
          <input type="hidden" />
        </form>
        <div>Weight</div>
        <div>Qty</div>
        <Button
          size="icon"
          variant="ghost"
          className=""
          onClick={() => deleteCategory.mutate(category.id)}
        >
          <Delete className="h-4 w-4" />
        </Button>
      </div>
      {category.items.map((item) => (
        <CategoryItem key={item.id} list={list} item={item} />
      ))}
      <Button size="sm" variant="linkMuted" className="mt-2">
        <Plus className="h-4 w-4 mr-2" />
        Add Gear
      </Button>
    </article>
  );
};
