// client-sveltekit/src/lib/components/Item.svelte
<script lang="ts">
  import ItemImage from "./ItemImage.svelte";
  import type { RecordModel } from "pocketbase";

  export let item: RecordModel;
</script>

<section class="py-2 text-sm flex gap-2 items-center">
  <ItemImage {item} />
  <div class="w-full">
    <div class="flex w-full justify-between items-center">
      <span>{item.name}</span>
      <span>{item.weight_g}g</span>
    </div>
    <p class="text-muted-foreground">{item.description}</p>
  </div>
</section>

// react-spa-pb/src/components/Item.tsx
import { RecordModel } from "pocketbase";
import React from "react";

interface Props {
  item: RecordModel;
}

export const Item: React.FC<Props> = (props) => {
  const { item } = props;
  return (
    <div className="text-sm">
      <h3 className="">{item.name}</h3>
      <p className="text-muted-foreground">{item.description}</p>
    </div>
  );
};
