// client/src/components/ListSettings.svelte
<script lang="ts">
  import { Settings } from "lucide-svelte";
  import { Button } from "./ui/button";
  import {
    DropdownMenu,
    DropdownMenuCheckboxItem,
    DropdownMenuContent,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
  } from "./ui/dropdown-menu";
  import type { RecordModel } from "pocketbase";
  import { useUpdateList } from "@/hooks/useList";

  export let list: RecordModel;

  $: updateList = useUpdateList();
  $: saveList = () => $updateList.mutate(list);
</script>

<DropdownMenu>
  <DropdownMenuTrigger asChild let:builder>
    <Button builders={[builder]} size="icon" variant="secondary" class="h-full">
      <Settings class="h-4 w-4" />
    </Button>
  </DropdownMenuTrigger>
  <DropdownMenuContent>
    <DropdownMenuLabel>List Settings</DropdownMenuLabel>
    <DropdownMenuSeparator />
    <DropdownMenuCheckboxItem
      bind:checked={list.show_packed}
      onCheckedChange={saveList}
    >
      Show Packed
    </DropdownMenuCheckboxItem>
    <DropdownMenuCheckboxItem
      bind:checked={list.show_images}
      onCheckedChange={saveList}
    >
      Show Images
    </DropdownMenuCheckboxItem>
    <DropdownMenuCheckboxItem
      bind:checked={list.show_weights}
      onCheckedChange={saveList}
    >
      Show Weight
    </DropdownMenuCheckboxItem>
    <DropdownMenuCheckboxItem
      bind:checked={list.show_prices}
      onCheckedChange={saveList}
    >
      Show Prices
    </DropdownMenuCheckboxItem>
  </DropdownMenuContent>
</DropdownMenu>

// react-spa-pb/src/components/ListSettings.tsx
import React from "react";
import { buttonVariants } from "./ui/button";
import { Settings } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import { RecordModel } from "pocketbase";
import { useDataQuery } from "@/hooks/useDataQuery";
import { cn } from "@/lib/utils";

interface Props {
  list: RecordModel;
}

export const ListSettings: React.FC<Props> = (props) => {
  const { list } = props;
  const { updateList } = useDataQuery();

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        className={cn(
          buttonVariants({ variant: "secondary", size: "icon" }),
          "h-full"
        )}
      >
        <Settings className="h-4 w-4" />
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        <DropdownMenuLabel>List Settings</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuCheckboxItem
          checked={list.show_packed}
          onCheckedChange={(checked) =>
            updateList.mutate({ id: list.id, data: { show_packed: checked } })
          }
        >
          Show Packed
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          checked={list.show_images}
          onCheckedChange={(checked) =>
            updateList.mutate({ id: list.id, data: { show_images: checked } })
          }
        >
          Show Images
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          checked={list.show_weights}
          onCheckedChange={(checked) =>
            updateList.mutate({ id: list.id, data: { show_weights: checked } })
          }
        >
          Show Weight
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem
          checked={list.show_prices}
          onCheckedChange={(checked) =>
            updateList.mutate({ id: list.id, data: { show_prices: checked } })
          }
        >
          Show Prices
        </DropdownMenuCheckboxItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
