// client-sk/src/routes/(app)/[listId]/ListHeader.svelte
<script lang="ts">
  import { Input } from "../../../components/ui/input";
  import { Textarea } from "../../../components/ui/textarea";
  import { useUpdateList, type ListWithCategories } from "@/hooks/useList";
  import ListSettings from "./ListSettings.svelte";

  export let list: ListWithCategories;

  $: updateList = useUpdateList();
  $: saveList = () => $updateList.mutate({ id: list.id, list });
</script>

<div class="flex gap-2">
  <form on:submit={saveList} class="flex-1 space-y-2">
    <Input
      bind:value={list.name}
      on:blur={saveList}
      class="text-primary h-auto text-3xl font-bold placeholder:italic"
      placeholder="List Name"
    />
    <Textarea
      bind:value={list.description}
      on:blur={saveList}
      class="placeholder:italic"
      placeholder="Description"
    />
    <input type="hidden" />
  </form>
  <div class="flex gap-2">
    <ListSettings {list} />
  </div>
</div>

// react-spa-pb/src/components/ListHeader.tsx
import type { RecordModel } from "pocketbase";
import React from "react";
import { Controller, useForm } from "react-hook-form";
import { Textarea } from "@/components/ui/textarea";
import { ListWithCategories, useDataQuery } from "@/hooks/useDataQuery";
import { Input } from "./ui/input";
import { ListSettings } from "./ListSettings";

interface Props {
  list: ListWithCategories;
}

export const ListHeader: React.FC<Props> = (props) => {
  const { list } = props;
  const { updateList } = useDataQuery();

  const methods = useForm({
    values: list,
  });

  const { handleSubmit, control } = methods;

  const saveList = (data: RecordModel) =>
    updateList.mutate({ id: list.id, data });

  return (
    <div className="flex gap-2">
      <form
        onBlur={handleSubmit(saveList)}
        onSubmit={handleSubmit(saveList)}
        className="space-y-2 flex-1"
      >
        <Controller
          control={control}
          name="name"
          render={({ field }) => (
            <Input
              {...field}
              className="h-auto text-3xl text-primary font-bold"
              placeholder="List Name"
            />
          )}
        />
        <Controller
          control={control}
          name="description"
          render={({ field }) => (
            <Textarea {...field} placeholder="Description" />
          )}
        />
        <input type="hidden" />
      </form>
      <div className="flex gap-2">
        <ListSettings list={list} />
      </div>
    </div>
  );
};
