// react-spa-pb/src/components/LoginForm.tsx
import React from "react";
import { Form, FormControl, FormField, FormItem, FormMessage } from "./ui/form";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "./ui/card";
import { Input } from "./ui/input";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "./ui/button";
import { pb } from "@/lib/pocketbase";
import { useNavigate } from "react-router-dom";
import { ClientResponseError } from "pocketbase";
import { AlertTriangle } from "lucide-react";
import { Alert, AlertTitle, AlertDescription } from "./ui/alert";
import { useForm } from "react-hook-form";
import { toast } from "sonner";

const schema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
});
type Schema = z.infer<typeof schema>;

export const LoginForm: React.FC = () => {
  const navigate = useNavigate();

  const methods = useForm<Schema>({
    resolver: zodResolver(schema),
    defaultValues: { email: "", password: "" },
    mode: "onChange",
  });
  const { control, handleSubmit } = methods;

  const [error, setError] = React.useState<string | null>(null);

  const submitForm = async (data: Schema) => {
    try {
      await pb.collection("users").authWithPassword(data.email, data.password);
      toast.success("Successfully Logged in");
      navigate("/");
    } catch (error) {
      console.error((error as ClientResponseError).data);
      setError((error as ClientResponseError).data.message);
    }
  };

  return (
    <Form {...methods}>
      <form onSubmit={handleSubmit(submitForm)}>
        {error && (
          <Alert variant="destructive" className="mb-1">
            <AlertTriangle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}
        <Card>
          <CardHeader>
            <CardTitle>Login</CardTitle>
            <CardDescription>Enter your credentials</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            <FormField
              control={control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <Input type="email" placeholder="Email" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <Input type="password" placeholder="Password" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </CardContent>
          <CardFooter>
            <Button type="submit" className="w-full">
              Submit
            </Button>
          </CardFooter>
        </Card>
      </form>
    </Form>
  );
};

// svelte-spa-pb/src/components/forms/LoginForm.svelte
<script lang="ts">
  import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
  import { Button } from "@/components/ui/button";
  import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
  } from "@/components/ui/card";
  import { Input } from "@/components/ui/input";
  import { pb } from "@/lib/pocketbase";
  import { AlertTriangle } from "lucide-svelte";
  import type { ClientResponseError } from "pocketbase";

  type Schema = { email: string; password: string };
  type PbValidationError = { message: string; code: string };

  let data: Schema = {
    email: "",
    password: "",
  };

  let error: {
    identity?: PbValidationError;
    password?: PbValidationError;
    overall?: string;
  } = {};

  const submitForm = (data: Schema) =>
    pb
      .collection("users")
      .authWithPassword(data.email, data.password)
      .then((res) => {
        console.log("login successful");
        window.location.href = "/";
      })
      .catch((err: ClientResponseError) => {
        console.log(err.data);
        error = { ...error, ...err.data.data };
        error.overall = err.data.message;
      });
</script>

<form on:submit|preventDefault={() => submitForm(data)}>
  {#if error.overall}
    <Alert variant="destructive" class="mb-2">
      <AlertTriangle className="h-4 w-4" />
      <AlertTitle>Error</AlertTitle>
      <AlertDescription>{error.overall}</AlertDescription>
    </Alert>
  {/if}
  <Card>
    <CardHeader>
      <CardTitle>Login</CardTitle>
      <CardDescription>Enter your credentials</CardDescription>
    </CardHeader>
    <CardContent class="space-y-2">
      <Input
        placeholder="Email"
        type="email"
        name="email"
        bind:value={data.email}
      />
      {#if error.identity}
        <span class="text-xs text-destructive">{error.identity.message}</span>
      {/if}
      <Input
        placeholder="Password"
        type="password"
        name="password"
        bind:value={data.password}
      />
      {#if error.password}
        <span class="text-xs text-destructive">{error.password.message}</span>
      {/if}
    </CardContent>
    <CardFooter>
      <Button type="submit" class="w-full">Submit</Button>
    </CardFooter>
  </Card>
</form>
