// client-react/src/routes/auth.tsx
import LoginForm from "@/components/forms/login-form";
import SignupForm from "@/components/forms/signup-form";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import { Feather } from "lucide-react";
import React from "react";

export default function AuthPage(): ReturnType<React.FC> {
  return (
    <div className="flex w-full h-full items-center justify-center">
      <div className="max-w-xs w-full max-h-[80vh] h-full">
        <div className="mb-8 flex flex-col items-center">
          <Feather size="4rem" className="mb-4 text-primary" />
          <h1 className="mb-1 text-3xl font-bold">PackLighter</h1>
          <p className="text-sm text-muted-foreground">
            The packing tool of champions
          </p>
        </div>
        <Tabs defaultValue="login" className="flex flex-col gap-4">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="login">Login</TabsTrigger>
            <TabsTrigger value="signup">Sign Up</TabsTrigger>
          </TabsList>
          <TabsContent value="login">
            <LoginForm />
          </TabsContent>
          <TabsContent value="signup">
            <SignupForm />
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}

// svelte-spa-pb/src/routes/auth/+page.svelte
<script>
	import LoginForm from '$components/forms/LoginForm.svelte';
	import { Tabs, TabsContent, TabsList, TabsTrigger } from '$components/ui/tabs';
	import { Feather } from 'lucide-svelte';
</script>

<div class="container max-w-sm py-12">
	<div class="flex flex-col mb-8 items-center">
		<Feather class="h-16 w-16 text-primary mb-4" />
		<h1 class="text-3xl font-bold mb-1">PackLighter</h1>
		<p class="text-sm text-muted-foreground">The packing tool of champions</p>
	</div>
	<Tabs value="login">
		<TabsList class="grid w-full grid-cols-2">
			<TabsTrigger value="login">Login</TabsTrigger>
			<TabsTrigger value="signup">Sign Up</TabsTrigger>
		</TabsList>
		<TabsContent value="login">
			<LoginForm />
		</TabsContent>
		<TabsContent value="signup">
			<!-- <SignUpForm /> -->
		</TabsContent>
	</Tabs>
</div>
