// src/components/account-editor.tsx
import React from "react";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { AtSign, Lock, LogOut, Trash, User } from "lucide-react";
import { getProfilePhoto } from "@/actions/auth";
import { pb } from "@/lib/pocketbase";
import { useNavigate } from "react-router-dom";
import { queryClient } from "@/lib/query";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { getPaths } from "@/lib/utils";

export default function AccountEditor(): ReturnType<React.FC> {
  const user = pb.authStore.model;
  const imageUrl = getProfilePhoto();

  const [isEmailDialogOpen, setIsEmailDialogOpen] = React.useState(false);
  const [isPasswordDialogOpen, setIsPasswordDialogOpen] = React.useState(false);
  const [isDeteteDialogOpen, setIsDeleteDialogOpen] = React.useState(false);

  const navigate = useNavigate();

  const logout = () => {
    pb.authStore.clear();
    navigate(getPaths.auth());
    queryClient.removeQueries();
  };

  if (!user) return null;

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger>
          <div className="flex cursor-pointer items-center text-sm underline-offset-4 hover:underline">
            <Avatar className="h-10 w-10">
              <AvatarImage src={imageUrl} alt="@shadcn" />
              <AvatarFallback>
                <User className="h-8" />
              </AvatarFallback>
            </Avatar>
          </div>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <div className="flex gap-4 p-2">
            <Avatar className="h-16 w-16">
              <AvatarImage src={imageUrl} alt="@shadcn" />
              <AvatarFallback>
                <User size="3rem" />
              </AvatarFallback>
            </Avatar>
            <div className="flex flex-col justify-center">
              <h2 className="text-lg font-semibold">{user.name}</h2>
              <p className="text-muted-foreground text-sm">{user.email}</p>
            </div>
          </div>
          <DropdownMenuSeparator />
          <DropdownMenuGroup>
            <DropdownMenuLabel>Account Settings</DropdownMenuLabel>
            <DropdownMenuItem onClick={() => setIsEmailDialogOpen(true)}>
              Change Email
              <DropdownMenuShortcut>
                <AtSign size="1rem" />
              </DropdownMenuShortcut>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setIsPasswordDialogOpen(true)}>
              Change Password
              <DropdownMenuShortcut>
                <Lock size="1rem" />
              </DropdownMenuShortcut>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setIsDeleteDialogOpen(true)}>
              Delete Account
              <DropdownMenuShortcut>
                <Trash size="1rem" />
              </DropdownMenuShortcut>
            </DropdownMenuItem>
          </DropdownMenuGroup>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={logout}>
            Logout
            <DropdownMenuShortcut>
              <LogOut size="1rem" />
            </DropdownMenuShortcut>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </>
  );
}

// client-sk/src/components/AccountEditor.svelte
<script lang="ts">
  import { pb } from "@/lib/pocketbase";
  import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
  import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
  import { User } from "lucide-svelte";
  import { Separator } from "@/components/ui/separator";
  import { Button } from "@/components/ui/button";
  import { push } from "svelte-spa-router";

  const user = pb.authStore.model;
  const imageUrl = user
    ? pb.files.getUrl(user, user.avatar, { thumb: "100x100" })
    : "";
</script>

<Sheet>
  <SheetTrigger>
    <div
      class="flex cursor-pointer items-center text-sm underline-offset-4 hover:underline"
    >
      <Avatar class="h-10 w-10">
        <AvatarImage src={imageUrl} alt="@shadcn" />
        <AvatarFallback>
          <User class="h-8" />
        </AvatarFallback>
      </Avatar>
    </div>
  </SheetTrigger>
  <SheetContent class="flex flex-col">
    {#if user}
      <div class="flex gap-4">
        <Avatar class="h-20 w-20">
          <AvatarImage src={imageUrl} alt="@shadcn" />
          <AvatarFallback>
            <User class="h-8" />
          </AvatarFallback>
        </Avatar>
        <div class="flex flex-col justify-center">
          <h2 class="text-lg font-semibold">{user.name}</h2>
          <p class="text-sm text-muted-foreground">{user.email}</p>
        </div>
      </div>
      <Separator class="my-4" />
      <div class="flex-1"></div>
      <Button
        type="submit"
        class="w-full"
        on:click={() => {
          pb.authStore.clear();
          push("/auth");
        }}
      >
        Logout
      </Button>
    {:else}
      Not logged in
    {/if}
  </SheetContent>
</Sheet>
