// client/src/components/forms/SignUpForm.svelte
<script lang="ts">
  import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
  import { Button } from "@/components/ui/button";
  import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
  } from "@/components/ui/card";
  import { Input } from "@/components/ui/input";
  import { pb } from "@/lib/pocketbase";
  import { AlertTriangle } from "lucide-svelte";
  import type { ClientResponseError } from "pocketbase";

  type Schema = {
    email: string;
    password: string;
    passwordConfirm: string;
    username: string;
  };
  type PbValidationError = { message: string; code: string };

  let data: Schema = {
    email: "",
    password: "",
    passwordConfirm: "",
    username: "",
  };

  let error: {
    identity?: PbValidationError;
    password?: PbValidationError;
    passwordConfirm?: PbValidationError;
    username?: PbValidationError;
    overall?: string;
  } = {};

  const submitForm = (data: Schema) =>
    pb
      .collection("users")
      .create(data)
      .then((res) => {
        console.log("account creation successful");
        window.location.href = "/";
      })
      .catch((err: ClientResponseError) => {
        console.log(err.data);
        error = { ...error, ...err.data.data };
        error.overall = err.data.message;
      });
</script>

<form on:submit|preventDefault={() => submitForm(data)}>
  {#if error.overall}
    <Alert variant="destructive" class="mb-2">
      <AlertTriangle className="h-4 w-4" />
      <AlertTitle>Error</AlertTitle>
      <AlertDescription>{error.overall}</AlertDescription>
    </Alert>
  {/if}
  <Card>
    <CardHeader>
      <CardTitle>Sign Up</CardTitle>
      <CardDescription>Create a new account</CardDescription>
    </CardHeader>
    <CardContent class="space-y-2">
      <Input
        placeholder="Username"
        type="text"
        name="username"
        bind:value={data.username}
      />
      {#if error.username}
        <span class="text-xs text-destructive">{error.username.message}</span>
      {/if}
      <Input
        placeholder="Email"
        type="email"
        name="email"
        bind:value={data.email}
      />
      {#if error.identity}
        <span class="text-xs text-destructive">{error.identity.message}</span>
      {/if}
      <Input
        placeholder="Password"
        type="password"
        name="password"
        bind:value={data.password}
      />
      {#if error.password}
        <span class="text-xs text-destructive">{error.password.message}</span>
      {/if}
      <Input
        placeholder="Password Confirm"
        type="password"
        name="passwordConfirm"
        bind:value={data.passwordConfirm}
      />
      {#if error.passwordConfirm}
        <span class="text-xs text-destructive"
          >{error.passwordConfirm.message}</span
        >
      {/if}
    </CardContent>
    <CardFooter>
      <Button type="submit" class="w-full">Submit</Button>
    </CardFooter>
  </Card>
</form>

// client-vite/src/components/signUpForm.tsx
import React from "react";
import { Form, FormControl, FormField, FormItem, FormMessage } from "./ui/form";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "./ui/card";
import { Input } from "./ui/input";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "./ui/button";
// import { AlertTriangle } from "lucide-react";
// import { Alert, AlertTitle, AlertDescription } from "../ui/alert";

const schema = z
  .object({
    name: z.string().min(3),
    email: z.string().email(),
    password: z.string().min(6),
    confirmPassword: z.string().min(6),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "Passwords do not match",
    path: ["confirmPassword"],
  });
type Schema = z.infer<typeof schema>;

export const SignUpForm: React.FC = () => {
  const methods = useForm<Schema>({
    resolver: zodResolver(schema),
    defaultValues: { email: "", password: "" },
    mode: "onChange",
  });
  const { control, handleSubmit } = methods;

  const submitForm = async (data: Schema) => {
    console.log(data);
  };

  return (
    <Form {...methods}>
      <form onSubmit={handleSubmit(submitForm)}>
        {/* {error && (
          <Alert variant="destructive" className="mb-1">
            <AlertTriangle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )} */}
        <Card>
          <CardHeader>
            <CardTitle>Login</CardTitle>
            <CardDescription>Enter your credentials</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            <FormField
              control={control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <Input placeholder="Sir Edmund Hillary" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <Input
                      type="email"
                      placeholder="mount_ev@hotmail.com"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <Input type="password" placeholder="••••••••" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="confirmPassword"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <Input type="password" placeholder="••••••••" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </CardContent>
          <CardFooter>
            <Button type="submit" className="w-full">
              Submit
            </Button>
          </CardFooter>
        </Card>
      </form>
    </Form>
  );
};
