// src/components/base/delete-button.tsx
import React from "react";
import { Button } from "../ui/button";
import { Check, X } from "lucide-react";

interface Props {
  handleDelete: () => void;
  noConfirm?: boolean;
}

const DeleteButton: React.FC<Props> = (props) => {
  const { handleDelete, noConfirm } = props;

  const [isConfirming, setIsConfirming] = React.useState(false);
  const cancelDelete = () => setIsConfirming(false);

  React.useEffect(() => {
    if (!isConfirming) return;

    window.addEventListener("click", cancelDelete);
    return () => window.removeEventListener("click", cancelDelete);
  }, [isConfirming]);

  return (
    <Button
      size="icon"
      variant={isConfirming ? "destructive" : "ghostMuted"}
      className="h-6 w-6 rounded-full"
      onClick={(ev) => {
        ev.stopPropagation();
        if (noConfirm) {
          handleDelete();
          return;
        }

        if (isConfirming) {
          handleDelete();
          setIsConfirming(false);
          return;
        }

        setIsConfirming(true);
      }}
    >
      {isConfirming ? <Check className="h-4 w-4" /> : <X className="h-4 w-4" />}
    </Button>
  );
};

export default DeleteButton;

// client/src/components/DeleteButton.svelte
<script>
  import { Check, X } from "lucide-svelte";
  import { Button } from "./ui/button";
  import { onDestroy, onMount } from "svelte";

  export let handleDelete = () => {};
  export let noConfirm = false;

  let isConfirming = false;

  const cancelDelete = () => {
    isConfirming = false;
  };

  onMount(() => {
    window.addEventListener("click", cancelDelete);
  });
  onDestroy(() => {
    window.removeEventListener("click", cancelDelete);
  });
</script>

<Button
  size="icon"
  variant={isConfirming ? "destructive" : "ghostMuted"}
  class="h-6 w-6 rounded-full"
  on:click={(ev) => {
    ev.stopPropagation();
    if (noConfirm) {
      handleDelete();
      return;
    }

    if (isConfirming) {
      handleDelete();
      isConfirming = false;
      return;
    }

    isConfirming = true;
  }}
>
  {#if isConfirming}
    <Check class="h-4 w-4" />
  {:else}
    <X class="h-4 w-4" />
  {/if}
</Button>
