// client-astro/src/components/ItemImage.tsx
import {
  Dialog,
  DialogTitle,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "./ui/button";
import { Input } from "./ui/input";

import React from "react";

import { cn } from "@/lib/utils";
import { Save } from "lucide-react";
import type { ItemType } from "@/lib/schema";

interface Props {
  item: ItemType;
}

export const ItemImage: React.FC<Props> = ({ item }) => {
  const [url, setUrl] = React.useState(item.image_url);
  return (
    <Dialog>
      <DialogTrigger>
        <div
          className={cn(
            "h-12 p-0.5 aspect-square rounded-sm flex justify-center items-center",
            item.image_url ? "bg-white" : "bg-muted"
          )}
        >
          {item.image_url && (
            <img
              className="h-full w-full object-contain"
              src={item.image_url}
              alt={item.name}
            />
          )}
        </div>
      </DialogTrigger>
      <DialogContent className="p-4">
        <form action="/gear?/updateItem" method="post" className="grid gap-4">
          <input type="hidden" name="id" value={item.id} />
          <DialogHeader className="text-left">
            <DialogTitle>Update Image</DialogTitle>
            <DialogDescription>Provide a link to an image</DialogDescription>
          </DialogHeader>
          <Input name="image_url" type="url" placeholder="Image URL" />
          {url ? (
            <div className="bg-white rounded-md p-2 flex items-center aspect-square justify-center">
              <img
                className="object-contain h-full w-full"
                src={url}
                alt={item.name}
              />
            </div>
          ) : (
            <div className="rounded-md bg-muted w-full p-4 flex items-center justify-center text-muted-foreground">
              No Image
            </div>
          )}
          <DialogFooter>
            <Button type="submit" disabled={url === item.image_url}>
              <Save className="h-4 w-4 mr-2" />
              Save
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

// client/src/components/ItemImage.svelte
<script lang="ts">
  import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
  } from "./ui/dialog";
  import { Loader2, Save } from "lucide-svelte";
  import { Button } from "./ui/button";
  import { cn } from "@/lib/utils";
  import { useUpdateItem } from "@/hooks/useItem";
  import { Input } from "./ui/input";
  import type { ItemsResponse } from "@/lib/types";

  export let item: ItemsResponse;

  let url = item.image_url;
  let isOpen = false;

  const updateItem = useUpdateItem();

  $: saveItem = () => {
    $updateItem.mutate({ id: item.id, item: { image_url: url } });
    isOpen = false;
  };
</script>

<Dialog closeOnEscape bind:open={isOpen}>
  <DialogTrigger>
    <div
      class={cn(
        "flex aspect-square w-20 items-center justify-center rounded-sm p-0.5",
        item.image_url ? "bg-white" : "bg-muted",
      )}
    >
      {#if item.image_url}
        <img
          class="h-full w-full object-contain"
          src={item.image_url}
          alt={item.name}
        />
      {/if}
    </div>
  </DialogTrigger>
  <DialogContent class="p-4">
    <DialogHeader class="text-left">
      <DialogTitle>Update {item.name} Image</DialogTitle>
      <DialogDescription>Provide a link to an image</DialogDescription>
    </DialogHeader>
    <form on:submit={saveItem} class="grid gap-4">
      <Input type="url" placeholder="Image URL" bind:value={url} />

      {#if url}
        <div
          class="flex aspect-square items-center justify-center rounded-md bg-white p-2"
        >
          <img class="h-full w-full object-contain" src={url} alt={item.name} />
        </div>
      {:else}
        <div
          class="bg-muted text-muted-foreground flex w-full items-center justify-center rounded-md p-4"
        >
          No Image
        </div>
      {/if}
      <DialogFooter>
        <Button
          type="submit"
          disabled={$updateItem.isPending || url === item.image_url}
        >
          {#if $updateItem.isPending}
            <Loader2 class="mr-2 h-4 w-4 animate-spin" />
          {:else}
            <Save class="mr-2 h-4 w-4" />
          {/if}
          Save
        </Button>
      </DialogFooter>
      <input type="hidden" />
    </form>
  </DialogContent>
</Dialog>
