// client-react/src/components/packing-lists.tsx
import { createList, getLists } from "@/api/list";
import { queryClient } from "@/lib/query";
import { Collections, ListsResponse } from "@/lib/types";
import { Plus } from "lucide-react";
import React from "react";
import { useMutation, useQuery } from "react-query";
import { useNavigate } from "react-router-dom";
import { Button } from "./ui/button";
import { Card } from "./ui/card";
import PackingList from "./packing-list";
import Loader from "./base/loader";
import Error from "./base/error";

export default function PackingLists(): ReturnType<React.FC> {
  const navigate = useNavigate();

  const listsQuery = useQuery<ListsResponse[], Error>({
    queryKey: [Collections.Lists],
    queryFn: getLists,
  });

  const newListMutation = useMutation({
    mutationFn: createList,
    onSuccess: (data) => {
      queryClient.invalidateQueries(Collections.Lists);
      navigate(`/list/${data.id}`);
    },
  });

  return (
    <div className="flex flex-col h-[40vh] gap-2 p-4">
      <header className="flex items-center justify-between">
        <span className="font-semibold text-sm">Lists</span>
        <Button
          size="sm"
          variant="linkMuted"
          onClick={() => newListMutation.mutate()}
        >
          <Plus size="1rem" className="mr-2" />
          Add List
        </Button>
      </header>
      <Card className="py-2 h-full overflow-y-auto">
        {listsQuery.isLoading && <Loader />}
        {listsQuery.isError && <Error message={listsQuery.error?.message} />}
        {listsQuery.data?.map((list) => (
          <PackingList key={list.id} list={list} />
        ))}
      </Card>
    </div>
  );
}

// client/src/components/PackingLists.svelte
<script lang="ts">
	import { Loader2, Plus } from 'lucide-svelte';
	import { Button } from '@/components/ui/button';

	import { useCreateList, useLists, useUpdateListsOrder } from '@/hooks/useList';
	import { SHADOW_ITEM_MARKER_PROPERTY_NAME, dndzone } from 'svelte-dnd-action';
	import { Collections, type ListsResponse } from '@/lib/types';
	import { flip } from 'svelte/animate';
	import { flipDurationMs } from '@/lib/constants';
	import ListListItem from './PackingList.svelte';
	import DragGhost from '@/components/base/DragGhost.svelte';
	import { transformDraggedElement } from '@/lib/helpers';
	import { createQuery } from '@tanstack/svelte-query';
	import { getLists } from '@/api/list';
	import IconTitleSubtitle from './base/IconTitleSubtitle.svelte';
	import Loader from './base/Loader.svelte';

	type ListWithShadowItem = ListsResponse & {
		[SHADOW_ITEM_MARKER_PROPERTY_NAME]?: string;
	};

	$: listsQuery = createQuery({
		queryFn: getLists,
		queryKey: [Collections.Lists]
	});
	$: createList = useCreateList();

	$: listData = ($listsQuery.data ?? []) as ListWithShadowItem[];

	$: updateListOrder = useUpdateListsOrder();
	const handleConsider = (ev: CustomEvent<DndEvent<ListsResponse>>) => {
		listData = ev.detail.items;
	};

	const handleFinalize = (ev: CustomEvent<DndEvent<ListsResponse>>) => {
		listData = ev.detail.items;
		const ids = ev.detail.items.map((item) => item.id);
		$updateListOrder.mutate({ listIds: ids });
	};
</script>

<section class="flex h-full max-h-[40vh] flex-1 flex-col gap-2 p-4">
	<div class="flex items-center justify-between">
		<h2 class="text-sm font-medium">Lists</h2>
		<Button size="sm" variant="linkMuted" on:click={() => $createList.mutate()}>
			<Plus class="mr-2 w-4" /> New List
		</Button>
	</div>
	<div
		use:dndzone={{
			items: listData,
			type: 'lists',
			flipDurationMs,
			dropTargetStyle: {},
			dropTargetClasses: ['border-primary'],
			transformDraggedElement
		}}
		on:consider={handleConsider}
		on:finalize={handleFinalize}
		class="bg-card h-full overflow-y-auto rounded-md border py-2 transition-colors"
	>
		{#if $listsQuery.isSuccess}
			{#each listData as list (list.id)}
				<div animate:flip={{ duration: flipDurationMs }} class="relative">
					<ListListItem {list} />
					{#if list[SHADOW_ITEM_MARKER_PROPERTY_NAME]}
						<DragGhost fullWidth />
					{/if}
				</div>
			{/each}
			{#if listData.length === 0}
				<p class="text-muted-foreground flex h-full items-center justify-center p-6 text-sm">
					No lists
				</p>
			{/if}
		{/if}

		{#if $listsQuery.isLoading}
			<Loader />
		{/if}
	</div>
</section>
