// client-react/src/components/item-image.tsx
import React from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "./ui/dialog";
import { Input } from "./ui/input";
import { Button } from "./ui/button";
import { Trash } from "lucide-react";
import { Collections, ItemsResponse } from "@/lib/types";
import { cn } from "@/lib/utils";
import { pb } from "@/lib/pocketbase";
import { useMutation } from "react-query";
import { deleteItemImage, setItemImage } from "@/api/item";
import { toast } from "sonner";
import { queryClient } from "@/lib/query";
import { useParams } from "react-router-dom";

interface Props {
  item: ItemsResponse;
}

const ItemImage: React.FC<Props> = (props) => {
  const { item } = props;

  const [isOpen, setIsOpen] = React.useState(false);
  const { listId } = useParams();

  const updateMutation = useMutation({
    mutationFn: (image: Blob) => setItemImage({ id: item.id, image }),
    onSuccess: () => {
      toast.success(`${item.name} image updated`);
      queryClient.invalidateQueries([Collections.Items]);
      queryClient.invalidateQueries([Collections.Lists, listId]);
    },
  });

  const deleteMutation = useMutation({
    mutationFn: () => deleteItemImage(item.id),
    onSuccess: () => {
      queryClient.invalidateQueries([Collections.Items]);
      queryClient.invalidateQueries([Collections.Lists, listId]);
      toast.success(`${item.name} image deleted`);
    },
  });

  React.useEffect(() => {
    const pasteFiles = (e: ClipboardEvent) => {
      if (isOpen && e.clipboardData?.files?.length) {
        updateMutation.mutate(e.clipboardData.files[0]);
      }
    };

    document.addEventListener("paste", pasteFiles);
    return () => {
      document.removeEventListener("paste", pasteFiles);
    };
  }, [isOpen, updateMutation]);

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger className="h-full">
        <div
          className={cn(
            "flex w-20 flex-1 items-center justify-center rounded-sm p-0.5",
            item.image ? "aspect-square bg-white" : "bg-muted/50 h-full",
            "outline-primary outline-1 transition-all hover:outline"
          )}
        >
          {item.image && (
            <img
              className="h-full w-full object-contain"
              src={pb.files.getUrl(item, item.image, { thumb: "80x80" })}
              alt={item.name}
            />
          )}
        </div>
      </DialogTrigger>
      <DialogContent className="p-4">
        <DialogHeader className="text-left">
          <DialogTitle>Update {item.name} Image</DialogTitle>
          <DialogDescription>
            Upload or provide a link to an image
          </DialogDescription>
        </DialogHeader>
        <Input
          type="file"
          accept="image/*"
          onChange={(e) => {
            const target = e.target as HTMLInputElement;
            if (target.files) {
              updateMutation.mutate(target.files[0]);
            }
          }}
        />

        <div
          className={cn(
            "text-muted-foreground flex aspect-square items-center justify-center rounded-md p-2",
            item.image ? "bg-white" : "bg-muted"
          )}
        >
          {item.image ? (
            <img
              className="h-full w-full object-contain"
              src={pb.files.getUrl(item, item.image, { thumb: "500x500" })}
              alt={item.name}
            />
          ) : (
            "No Image"
          )}
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="destructive"
            disabled={deleteMutation.isLoading}
            onClick={() => deleteMutation.mutate()}
          >
            <Trash className="mr-2 h-4 w-4" />
            Delete Image
          </Button>
        </DialogFooter>
        <input type="hidden" />
      </DialogContent>
    </Dialog>
  );
};

export default ItemImage;

// client/src/routes/(app)/[listId]/ItemImage.svelte
<script lang="ts">
	import {
		Dialog,
		DialogContent,
		DialogDescription,
		DialogFooter,
		DialogHeader,
		DialogTitle,
		DialogTrigger
	} from '@/components/ui/dialog';
	import { Trash } from 'lucide-svelte';
	import { Button } from '@/components/ui/button';
	import { cn } from '@/lib/utils';
	import { useDeleteItemImage, useSetItemImage } from '@/hooks/useItem';
	import type { ItemsResponse } from '@/lib/types';
	import { pb } from '@/lib/pocketbase';
	import { onDestroy, onMount } from 'svelte';
	import { Input } from '@/components/ui/input';

	export let item: ItemsResponse;

	let isOpen = false;

	const setItemImage = useSetItemImage();
	const deleteItemImage = useDeleteItemImage();

	const pasteFiles = (e: ClipboardEvent) => {
		if (isOpen && e.clipboardData?.files?.length) {
			$setItemImage.mutate({ id: item.id, image: e.clipboardData.files[0] });
		}
	};

	const handleInputChange = (e: Event) => {
		const target = e.target as HTMLInputElement;
		if (target.files) {
			$setItemImage.mutate({ id: item.id, image: target.files[0] });
		}
	};

	onMount(() => window.addEventListener('paste', pasteFiles));
	onDestroy(() => window.removeEventListener('paste', pasteFiles));
</script>

<Dialog closeOnEscape bind:open={isOpen}>
	<DialogTrigger class="h-full">
		<div
			class={cn(
				'flex w-20 items-center justify-center rounded-sm p-0.5',
				item.image ? 'aspect-square bg-white' : 'bg-muted/50 h-full',
				'outline-primary outline-1 transition-all hover:outline'
			)}
		>
			{#if item.image}
				<img
					class="h-full w-full object-contain"
					src={pb.files.getUrl(item, item.image, { thumb: '80x80' })}
					alt={item.name}
				/>
			{/if}
		</div>
	</DialogTrigger>
	<DialogContent class="p-4">
		<DialogHeader class="text-left">
			<DialogTitle>Update {item.name} Image</DialogTitle>
			<DialogDescription>Upload or provide a link to an image</DialogDescription>
		</DialogHeader>
		<Input type="file" accept="image/*" on:change={handleInputChange} />

		<div
			class={cn(
				'text-muted-foreground flex aspect-square items-center justify-center rounded-md p-2',
				item.image ? 'bg-white' : 'bg-muted'
			)}
		>
			{#if item.image}
				<img
					class="h-full w-full object-contain"
					src={pb.files.getUrl(item, item.image, { thumb: '500x500' })}
					alt={item.name}
				/>
			{:else}
				No Image
			{/if}
		</div>

		<DialogFooter>
			<Button
				type="button"
				variant="destructive"
				disabled={$deleteItemImage.isPending}
				on:click={() => $deleteItemImage.mutate(item.id)}
			>
				<Trash class="mr-2 h-4 w-4" />
				Delete Image
			</Button>
		</DialogFooter>
		<input type="hidden" />
	</DialogContent>
</Dialog>
