// react-spa-pb/src/components/ItemListItem.tsx
import { GripVertical, X } from "lucide-react";
import { RecordModel } from "pocketbase";
import { Button } from "./ui/button";
import { useDataQuery } from "@/hooks/useDataQuery";
import { useDraggable } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";

interface Props {
  item: RecordModel;
}

export const ItemListItem: React.FC<Props> = ({ item }) => {
  const { deleteItem } = useDataQuery();

  const { attributes, listeners, setNodeRef, transform } = useDraggable({
    id: item.id,
  });

  const style = { transform: CSS.Translate.toString(transform) };

  return (
    <div
      {...attributes}
      style={style}
      ref={setNodeRef}
      className="text-sm pr-2 py-1 hover:bg-card transition-colors flex items-center gap-1"
    >
      <div {...listeners}>
        <GripVertical className="h-4 w-4 text-muted-foreground" />
      </div>
      <div className="flex-1">
        <h3 className="">{item.name}</h3>
        <p className="text-muted-foreground text-xs">{item.description}</p>
      </div>
      <Button
        size="icon"
        variant="ghost"
        className="h-6 w-6"
        onClick={() => deleteItem.mutate(item.id)}
      >
        <X className="h-4 w-4" />
      </Button>
    </div>
  );
};

// client-sk/src/routes/(app)/ItemListItem.svelte
<script lang="ts">
  import { useDeleteItem } from "@/hooks/useItem";
  import { cn } from "@/lib/utils";
  import type { ItemsResponse } from "@/lib/types";
  import DeleteButton from "../../components/base/DeleteButton.svelte";
  import DragHandle from "../../components/base/DragHandle.svelte";
  import { DRAGGABLE_CLASS } from "@/lib/constants";
  import { Item } from "../../components/ui/dropdown-menu";
  import { formatWeight } from "@/lib/helpers";

  export let item: ItemsResponse;

  const deleteItem = useDeleteItem();
</script>

<div
  id={item.id}
  data-id={item.id}
  class="{DRAGGABLE_CLASS} hover:bg-secondary/50 flex items-center gap-2 p-2 pl-4 text-sm transition-colors"
>
  <div class="flex-1">
    <h3 class={cn(!item.name && "text-muted-foreground italic")}>
      {item.name || "Unnamed Item"}
    </h3>
    <p class="text-muted-foreground">{item.description}</p>
  </div>
  <div class="text-muted-foreground">
    {item.weight}
    {item.weight_unit}
  </div>
  <DeleteButton handleDelete={() => $deleteItem.mutate(item.id)} />
</div>
