// react-spa-pb/src/components/CategoryItem.tsx
import { ExpandedCategoryItem, useDataQuery } from "@/hooks/useDataQuery";
import { Delete } from "lucide-react";
import React from "react";
import { Button } from "./ui/button";
import { Controller, useForm } from "react-hook-form";
import { Input } from "./ui/input";
import { ItemImage } from "./ItemImage";
import { RecordModel } from "pocketbase";
import { Checkbox } from "./ui/checkbox";

interface Props {
  list: RecordModel;
  item: ExpandedCategoryItem;
}

export const CategoryItem: React.FC<Props> = (props) => {
  const { item, list } = props;
  const { updateCategoryItem, deleteCategoryItem } = useDataQuery();

  const methods = useForm({
    values: item,
  });

  const { handleSubmit, control } = methods;

  const saveCategoryItem = (data: ExpandedCategoryItem) => {
    updateCategoryItem.mutate({
      id: item.id,
      itemId: item.itemData.id,
      data,
    });
  };

  return (
    <form
      className="border-b text-sm p-1 grid gap-2 items-center hover:bg-muted/30 transition-colors"
      style={{
        gridTemplateColumns: `${list.show_packed ? "auto" : ""} ${
          list.show_images ? "auto" : ""
        } 1fr 3fr 6rem 4rem auto`,
      }}
      onSubmit={handleSubmit(saveCategoryItem)}
      onBlur={handleSubmit(saveCategoryItem)}
    >
      {list.show_packed && (
        <Checkbox
          checked={item.packed}
          onCheckedChange={(checked) =>
            updateCategoryItem.mutate({
              id: item.id,
              data: { packed: checked },
            })
          }
        />
      )}
      {list.show_images && <ItemImage item={item.itemData} />}
      <Controller
        control={control}
        name="itemData.name"
        render={({ field }) => (
          <Input
            {...field}
            placeholder="Name"
            className="border-none shadow-none"
          />
        )}
      />
      <Controller
        control={control}
        name="itemData.description"
        render={({ field }) => (
          <Input
            {...field}
            placeholder="Description"
            className="text-muted-foreground border-none shadow-none"
          />
        )}
      />
      <Controller
        control={control}
        name="itemData.weight_g"
        render={({ field }) => (
          <Input
            {...field}
            type="number"
            min="0"
            className="border-none shadow-none"
          />
        )}
      />
      <Controller
        control={control}
        name="quantity"
        render={({ field }) => (
          <Input
            {...field}
            type="number"
            min="1"
            className="border-none shadow-none"
          />
        )}
      />
      <Button
        size="icon"
        variant="linkMuted"
        onClick={() => deleteCategoryItem.mutate(item.id)}
      >
        <Delete className="h-4 w-4" />
      </Button>
      <input type="hidden" />
    </form>
  );
};

// client-sk/src/routes/(app)/[listId]/CategoryItem.svelte
<script lang="ts">
  import type {
    ExpandedCategoryItem,
    ListWithCategories,
  } from "@/hooks/useList";
  import {
    useDeleteCategoryItem,
    useUpdateCategoryItem,
  } from "@/hooks/useCategoryItem";
  import { Checkbox } from "../../../components/ui/checkbox";
  import ItemImage from "./ItemImage.svelte";
  import {
    createCategoryTemplateCols,
    selectContentOnFocus,
  } from "@/lib/helpers";
  import { Input } from "../../../components/ui/input";
  import DeleteButton from "../../../components/base/DeleteButton.svelte";
  import DragHandle from "../../../components/base/DragHandle.svelte";
  import { DRAGGABLE_CLASS } from "@/lib/constants";
  import { ItemsWeightUnitOptions } from "@/lib/types";
  import { ChevronDown, ChevronUp } from "lucide-svelte";
  import { Button } from "../../../components/ui/button";
  import SpinBox from "../../../components/base/SpinBox.svelte";

  export let list: ListWithCategories;
  export let categoryItem: ExpandedCategoryItem;

  $: updateCategoryItem = useUpdateCategoryItem();
  $: deleteCategoryItem = useDeleteCategoryItem();

  $: saveCategoryItem = () => {
    $updateCategoryItem.mutate({ id: categoryItem.id, categoryItem });
  };
</script>

<form
  id={categoryItem.id}
  data-id={categoryItem.id}
  class="{DRAGGABLE_CLASS} hover:bg-muted grid items-center gap-2 border-b px-2 py-1 text-sm transition-colors"
  style="grid-template-columns: {createCategoryTemplateCols({
    list,
    type: 'body',
  })}"
  on:submit|preventDefault={saveCategoryItem}
>
  {#if list.show_packed}
    <Checkbox
      bind:checked={categoryItem.packed}
      onCheckedChange={saveCategoryItem}
    />
  {/if}

  {#if list.show_images}
    <ItemImage item={categoryItem.itemData} />
  {/if}

  <div class="@container">
    <div class="@md:grid-cols-[1fr_2fr] grid grid-cols-1 gap-x-2">
      <Input
        bind:value={categoryItem.itemData.name}
        on:blur={saveCategoryItem}
        name="name"
        placeholder="Name"
        class="h-auto w-full min-w-0 border-none bg-inherit py-0.5 shadow-none placeholder:italic"
      />

      <Input
        bind:value={categoryItem.itemData.description}
        on:blur={saveCategoryItem}
        name="description"
        placeholder="Description"
        class="text-muted-foreground h-auto w-full min-w-0 resize-none overflow-hidden border-none bg-inherit py-0.5 shadow-none placeholder:italic"
      />
    </div>
  </div>

  {#if list.show_weights}
    <div class="flex">
      <Input
        on:blur={saveCategoryItem}
        bind:value={categoryItem.itemData.weight}
        on:focus={selectContentOnFocus}
        name="weight"
        type="number"
        autocomplete="off"
        min="0"
        class="h-auto min-w-0 border-none px-1 py-0.5 text-right shadow-none"
      />
      <select
        bind:value={categoryItem.itemData.weight_unit}
        on:change={saveCategoryItem}
        class="bg-inherit"
      >
        {#each Object.values(ItemsWeightUnitOptions) as massUnit}
          <option value={massUnit}>
            {massUnit}
          </option>
        {/each}
      </select>
    </div>
  {/if}

  <div class="flex gap-0.5">
    <Input
      bind:value={categoryItem.quantity}
      on:change={saveCategoryItem}
      on:focus={selectContentOnFocus}
      name="quantity"
      type="number"
      autocomplete="off"
      min="1"
      class="h-auto min-w-0 border-none px-1 py-0.5 text-right shadow-none"
    />
    <SpinBox
      bind:value={categoryItem.quantity}
      handleChange={saveCategoryItem}
      min={1}
    />
  </div>

  <input type="hidden" />
  <DeleteButton
    handleDelete={() => $deleteCategoryItem.mutate(categoryItem)}
    noConfirm
  />
  <DragHandle />
</form>
